<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PessoaTelefone', 'doctrine');

/**
 * BasePessoaTelefone
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $pessoa_id
 * @property integer $telefone_id
 * @property Pessoa $Pessoa
 * @property Telefone $Telefone
 * 
 * @method integer        getId()          Returns the current record's "id" value
 * @method integer        getPessoaId()    Returns the current record's "pessoa_id" value
 * @method integer        getTelefoneId()  Returns the current record's "telefone_id" value
 * @method Pessoa         getPessoa()      Returns the current record's "Pessoa" value
 * @method Telefone       getTelefone()    Returns the current record's "Telefone" value
 * @method PessoaTelefone setId()          Sets the current record's "id" value
 * @method PessoaTelefone setPessoaId()    Sets the current record's "pessoa_id" value
 * @method PessoaTelefone setTelefoneId()  Sets the current record's "telefone_id" value
 * @method PessoaTelefone setPessoa()      Sets the current record's "Pessoa" value
 * @method PessoaTelefone setTelefone()    Sets the current record's "Telefone" value
 * 
 * @package    DemoJquery
 * @subpackage model
 * @author     Romeu Godoi <romeu.godoi@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePessoaTelefone extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pessoa_telefone');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('pessoa_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('telefone_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pessoa', array(
             'local' => 'pessoa_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Telefone', array(
             'local' => 'telefone_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}