<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Pessoa', 'doctrine');

/**
 * BasePessoa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nome
 * @property string $email
 * @property Doctrine_Collection $Enderecos
 * @property Doctrine_Collection $Telefones
 * @property Doctrine_Collection $PessoaEndereco
 * @property Doctrine_Collection $PessoaTelefone
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getNome()           Returns the current record's "nome" value
 * @method string              getEmail()          Returns the current record's "email" value
 * @method Doctrine_Collection getEnderecos()      Returns the current record's "Enderecos" collection
 * @method Doctrine_Collection getTelefones()      Returns the current record's "Telefones" collection
 * @method Doctrine_Collection getPessoaEndereco() Returns the current record's "PessoaEndereco" collection
 * @method Doctrine_Collection getPessoaTelefone() Returns the current record's "PessoaTelefone" collection
 * @method Pessoa              setId()             Sets the current record's "id" value
 * @method Pessoa              setNome()           Sets the current record's "nome" value
 * @method Pessoa              setEmail()          Sets the current record's "email" value
 * @method Pessoa              setEnderecos()      Sets the current record's "Enderecos" collection
 * @method Pessoa              setTelefones()      Sets the current record's "Telefones" collection
 * @method Pessoa              setPessoaEndereco() Sets the current record's "PessoaEndereco" collection
 * @method Pessoa              setPessoaTelefone() Sets the current record's "PessoaTelefone" collection
 * 
 * @package    DemoJquery
 * @subpackage model
 * @author     Romeu Godoi <romeu.godoi@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePessoa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pessoa');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nome', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Endereco as Enderecos', array(
             'refClass' => 'PessoaEndereco',
             'local' => 'pessoa_id',
             'foreign' => 'endereco_id'));

        $this->hasMany('Telefone as Telefones', array(
             'refClass' => 'PessoaTelefone',
             'local' => 'pessoa_id',
             'foreign' => 'telefone_id'));

        $this->hasMany('PessoaEndereco', array(
             'local' => 'id',
             'foreign' => 'pessoa_id'));

        $this->hasMany('PessoaTelefone', array(
             'local' => 'id',
             'foreign' => 'pessoa_id'));
    }
}