<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Telefone', 'doctrine');

/**
 * BaseTelefone
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $tipo_telefone_id
 * @property string $ddd
 * @property string $numero
 * @property TipoTelefone $TipoTelefone
 * @property Doctrine_Collection $Pessoa
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method integer             getTipoTelefoneId()   Returns the current record's "tipo_telefone_id" value
 * @method string              getDdd()              Returns the current record's "ddd" value
 * @method string              getNumero()           Returns the current record's "numero" value
 * @method TipoTelefone        getTipoTelefone()     Returns the current record's "TipoTelefone" value
 * @method Doctrine_Collection getPessoaTelefone()   Returns the current record's "PessoaTelefone" collection
 * @method Doctrine_Collection getPessoa()           Returns the current record's "Pessoa" collection
 * @method Telefone            setId()               Sets the current record's "id" value
 * @method Telefone            setTipoTelefoneId()   Sets the current record's "tipo_telefone_id" value
 * @method Telefone            setDdd()              Sets the current record's "ddd" value
 * @method Telefone            setNumero()           Sets the current record's "numero" value
 * @method Telefone            setTipoTelefone()     Sets the current record's "TipoTelefone" value
 * @method Telefone            setPessoaTelefone()   Sets the current record's "PessoaTelefone" collection
 * @method Telefone            setPessoa()           Sets the current record's "Pessoa" collectionTelefone
 * @property Doctrine_Collection $Pessoa
 * 
 * @package    DemoJquery
 * @subpackage model
 * @author     Romeu Godoi <romeu.godoi@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTelefone extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('telefone');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tipo_telefone_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('ddd', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('numero', 'string', 9, array(
             'type' => 'string',
             'fixed' => 1,
             'notnull' => true,
             'length' => 9,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoTelefone', array(
             'local' => 'tipo_telefone_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('PessoaTelefone', array(
             'local' => 'id',
             'foreign' => 'telefone_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Pessoa', array(
             'refClass' => 'PessoaTelefone',
             'local' => 'telefone_id',
             'foreign' => 'pessoa_id'));
    }
}