<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PessoaEndereco', 'doctrine');

/**
 * BasePessoaEndereco
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $pessoa_id
 * @property integer $endereco_id
 * @property Pessoa $Pessoa
 * @property Endereco $Endereco
 * 
 * @method integer        getId()          Returns the current record's "id" value
 * @method integer        getPessoaId()    Returns the current record's "pessoa_id" value
 * @method integer        getEnderecoId()  Returns the current record's "endereco_id" value
 * @method Pessoa         getPessoa()      Returns the current record's "Pessoa" value
 * @method Endereco       getEndereco()    Returns the current record's "Endereco" value
 * @method PessoaEndereco setId()          Sets the current record's "id" value
 * @method PessoaEndereco setPessoaId()    Sets the current record's "pessoa_id" value
 * @method PessoaEndereco setEnderecoId()  Sets the current record's "endereco_id" value
 * @method PessoaEndereco setPessoa()      Sets the current record's "Pessoa" value
 * @method PessoaEndereco setEndereco()    Sets the current record's "Endereco" value
 * 
 * @package    DemoJquery
 * @subpackage model
 * @author     Romeu Godoi <romeu.godoi@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePessoaEndereco extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pessoa_endereco');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('pessoa_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('endereco_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pessoa', array(
             'local' => 'pessoa_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Endereco', array(
             'local' => 'endereco_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}