<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Endereco', 'doctrine');

/**
 * BaseEndereco
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $tipo_endereco_id
 * @property string $endereco
 * @property string $cidade
 * @property string $uf
 * @property string $cep
 * @property TipoEndereco $TipoEndereco
 * @property Doctrine_Collection $Pessoa
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method integer             getTipoEnderecoId()   Returns the current record's "tipo_endereco_id" value
 * @method string              getEndereco()         Returns the current record's "endereco" value
 * @method string              getCidade()           Returns the current record's "cidade" value
 * @method string              getUf()               Returns the current record's "uf" value
 * @method string              getCep()              Returns the current record's "cep" value
 * @method TipoEndereco        getTipoEndereco()     Returns the current record's "TipoEndereco" value
 * @method Doctrine_Collection getPessoaEndereco()   Returns the current record's "PessoaEndereco" collection
 * @method Doctrine_Collection getPessoa()           Returns the current record's "Pessoa" collection
 * @method Endereco            setId()               Sets the current record's "id" value
 * @method Endereco            setTipoEnderecoId()   Sets the current record's "tipo_endereco_id" value
 * @method Endereco            setEndereco()         Sets the current record's "endereco" value
 * @method Endereco            setCidade()           Sets the current record's "cidade" value
 * @method Endereco            setUf()               Sets the current record's "uf" value
 * @method Endereco            setCep()              Sets the current record's "cep" value
 * @method Endereco            setTipoEndereco()     Sets the current record's "TipoEndereco" value
 * @method Endereco            setPessoaEndereco()   Sets the current record's "PessoaEndereco" collection
 * @method Endereco            setPessoa()           Sets the current record's "Pessoa" collectionEndereco
 * @property Doctrine_Collection $Pessoa
 * 
 * 
 * @package    DemoJquery
 * @subpackage model
 * @author     Romeu Godoi <romeu.godoi@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEndereco extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('endereco');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tipo_endereco_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('endereco', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('cidade', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('uf', 'string', 2, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('cep', 'string', 9, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 9,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoEndereco', array(
             'local' => 'tipo_endereco_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('PessoaEndereco', array(
             'local' => 'id',
             'foreign' => 'endereco_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Pessoa', array(
             'refClass' => 'PessoaEndereco',
             'local' => 'endereco_id',
             'foreign' => 'pessoa_id'));
    }
}