<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/01/12 18:46:56

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=demojquery;host=localhost',
  'username' => 'root',
  'password' => 123,
  'name' => 'doctrine',
)),);
