<?php

/**
 * Endereco
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Endereco extends BaseEndereco
{
	public function toArrayJSON()
	{
		$array = $this->toArray();
		
		if ($this->TipoEndereco instanceof TipoEndereco)
			$array['tipo_endereco'] = (string) $this->TipoEndereco;
		
		unset($array['TipoEndereco'], $array['PessoaEndereco']);
		
		return $array;
	}
}
