<?php

/**
 * EnderecoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EnderecoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EnderecoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Endereco');
    }
}