<?php

/**
 * PessoaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PessoaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PessoaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pessoa');
    }
}