<?php

/**
 * Pessoa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Pessoa extends BasePessoa
{
	public function toArrayJSON()
	{
		$array = $this->toArray();
		
		if ($this->Enderecos->count() > 0)
		{
			$enderecos = array();
			
			/* @var $endereco Endereco */
			foreach ($this->Enderecos as $key=>$endereco)
			{
				$enderecos[] = $endereco->toArrayJSON();
			}
			$array['enderecos'] = $enderecos;
		}
		if ($this->Telefones->count() > 0)
		{
			$enderecos = array();
			
			/* @var $telefone Telefone */
			foreach ($this->Telefones as $key=>$telefone)
			{
				$telefones[] = $telefone->toArrayJSON();
			}
			$array['telefones'] = $telefones;
		}
		unset($array['Enderecos'], $array['Telefones']);
		
		return $array;
	}
}
