<?php

/**
 * PessoaEnderecoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PessoaEnderecoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PessoaEnderecoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PessoaEndereco');
    }
}