<?php

/**
 * PessoaTelefoneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PessoaTelefoneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PessoaTelefoneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PessoaTelefone');
    }
}