<?php

/**
 * Telefone
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Telefone extends BaseTelefone
{
	public function toArrayJSON()
	{
		$array = $this->toArray();
		
		if ($this->TipoTelefone instanceof TipoTelefone)
			$array['tipo_telefone'] = (string) $this->TipoTelefone;
		
		unset($array['TipoTelefone'], $array['PessoaTelefone']);
		
		return $array;
	}	
}
