<?php

/**
 * TipoEnderecoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoEnderecoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoEnderecoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoEndereco');
    }
}